docker:
  - name: 'cleanup-backup-syncthing'
    type: 'exec'
    schedule: '0 0 12 * * *'
    command: 'foobar'
  - name: 'backup-radarr'
    type: 'run'
    image: 'alpine:latest'
    schedule: '0 0 14 * * *'
    command: "/bin/sh -c 'cp `ls -1 /source/Backups/scheduled/*.zip | sort | tail -n 1` /target/radarr_backup.zip"
  - name: 'bar'
    type: 'exec'
    schedule: '0 0 18 * * *'
  - name: 'foobar'
    type: 'exec'
    schedule: '0 20 20 * * *'
  - name: 'foobar_2'
    type: 'run'
    image: 'alpine:3.18.4'
    schedule: '0 20 20 * * *'
  - name: 'boofar'
    type: 'run'
    image: 'melvyndekort/scheduler:latest'
    schedule: '0 10 6 * * *'
