[tool.poetry]
name = "scheduler"
version = "0.1.0"
description = ""
authors = ["Melvyn de Kort <melvyn@mdekort.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
docker = "^7.0"
Flask = "^3.0"
gunicorn = "^21.2"
cachetools = "^5.3"
supervisor = "^4.2"
APScheduler = "^3.10"
slack-sdk = "^3.27"

[tool.poetry.dev-dependencies]
pytest = "^8.0"
pytest-cov = "^4.1"
pylint = "^3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
