[tool.poetry]
name = "scheduler"
version = "0.1.0"
description = ""
authors = ["Melvyn de Kort <melvyn@mdekort.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0.1"
docker = "^6.1.3"
Flask = "^3.0.0"
gunicorn = "^21.2.0"
cachetools = "^5.3.2"
supervisor = "^4.2.5"
APScheduler = "^3.10.4"
slack-sdk = "^3.23.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
